name: ci-build
run-name: CI Pipeline
on: [push] # to be replaced with proper condition

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout gRPC
      uses: actions/checkout@v4.2.2
      with:
        repository: grpc/grpc
        ref: v1.60.0
        path: grpc
        submodules: true

    - name: build gRPC
      uses: threeal/cmake-action@v2.1.0
      with:
        source-dir: ./grpc
        build-dir: ./grpc/build
        options: |
          ABSL_PROPAGATE_CXX_STD=ON
          CMAKE_BUILD_TYPE=Release
          CMAKE_INSTALL_PREFIX=$LocalPath/Install
          gRPC_INSTALL=ON
          gRPC_BUILD_TESTS=OFF
          gRPC_BACKWARDS_COMPATIBILITY_MODE=ON
        build-args: -j
    - name: checkout otel
      uses: actions/checkout@v4.2.2
      with:
        repository: open-telemetry/opentelemetry-cpp
        ref: v1.14.2
        path: otel
        submodules: true

    - name: build otel
      uses: threeal/cmake-action@v2.1.0
      with:
        source-dir: ./otel
        build-dir: ./otel/build
        options: |
          CMAKE_BUILD_TYPE=Release
          CMAKE_INSTALL_PREFIX=$LocalPath/Install
          CMAKE_POSITION_INDEPENDENT_CODE=ON
          BUILD_TESTING=OFF
          WITH_ABSEIL=ON
          WITH_EXAMPLES=OFF
          WITH_OTLP_GRPC=ON
          WITH_OTLP_HTTP=OFF
        build-args: -j
      # might not be present in ubuntu-latest runner:
      # -DCMAKE_C_COMPILER=icc
      # -DCMAKE_CXX_COMPILER=icpc



